version: 2 

sources:
  - name: shop
    database: postgres 
    schema: sql_basics
    tables:
      - name: orders
      - name: customer
      - name: product
      - name: order_line
      - name: order_status
    